title: Tomás Ahumada
logo: /assets/img/IMG_5967.JPG
# description: At the  <a href="https://www.google.com/maps/place/Lago+Pirihueico/@7.0029779,-80.2117727,4.55z/data=!4m5!3m4!1s0x961150ebbfc86ff5:0xbf3cc897b5f78e80!8m2!3d-39.9295707!4d-71.794868">Piriheico Lake.</a> 
description: At the  <a href="https://goo.gl/maps/zL7z2jnoS71bXHK57">Gemini South Observatory.</a> 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
